# Site settings
title: Mateus Gomes
description: Senior Software Engineer
baseurl: "" 
url: "https://mateusgomes.dev"
email: mateus@mateusgomes.dev
author: Mateus Gomes
# Build settings
markdown: kramdown
locale: "en-US"
remote_theme: raviriley/agency-jekyll-theme
analytics:
  google: G-TX1P3VPGJH
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Defaults
defaults:
  - 
    scope:
      path: "" 
    values:
      layout: "default"

# Collections
collections:
  portfolio:


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - .gitignore
