title: Mateus Gomes
lang: en
url: https://mateusgomes.dev
google_analytics: 
author:
  name: Mateus Gomes
  email: mateus@mateusgomes.dev
description: >
  I'm a software engineer, with a focus on web development. I'm passionate about technology, and I love to learn new things.
  I'm currently using Java, Angular, Golang, Spring Boot, Spring Batch, Kubernetes, Docker, and more.

minima:
  skin: dark
  date_format: "%b %-d, %Y"
  social_links:
    - { platform: devto,          user_url: "https://dev.to/mateusgms" }
    - { platform: github,         user_url: "https://github.com/mateusgms" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/mateusgms" }
    - { platform: stackoverflow,  user_url: "https://stackexchange.com/users/10041944/mateus-gomes" }
    - { platform: twitter,        user_url: "https://twitter.com/mateusgomes_dev" }

show_excerpts: false # set to true to show excerpts on the homepage

# Build settings
baseurl: /home
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag

