title: Mateus Gomes
description: Senior Software Engineer
baseurl: "" 
url: "https://mateusgomes.dev"
email: mateus@mateusgomes.dev
author: Mateus Gomes
markdown: kramdown
locale: "en-US"
theme: jekyll-whiteglass
analytics:
  google: G-TX1P3VPGJH
plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap

permalink: /:year/:month/:day/:title/
paginate_path: /posts/:num/
paginate: 5

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: category_archives
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - .gitignore




